### ISSUE TITLE
Is Agensgraph with Timescale working?

### ISSUE THREAD

**Issue by candysmurf** [mcaramma/sv2#1]
It's great that you integrated so many Postgres ecosystem together. I just want Timescale on the top of the Agensgraph. I removed other components but the image cannot run. I'm wondering if it worked for you? thanks

**Comment by pratikpparikh** [comment]
@candysmurf yest it does work.

**Comment by candysmurf** [comment]
@pratikpparikh, It's great to know. Let me give your repo once more try to see if it works for me. thank you

**Comment by candysmurf** [comment]
@pratikpparikh, the image built after I removed EdgeDB. When running it, the container died after a few seconds,  I got the following error in the container log:

```sh
 docker logs 8deb02                                                                                                                                                   
waiting for server to start.... done
server started
```

Any insight? thanks

**Comment by candysmurf** [comment]
yes, it worked by installing timescale as an extension of agensgraph. Thank you @pratikpparikh.
I'm going to close this issue.
